# Streamlit Dashboard Build and Deploy Pipeline
#
# This pipeline builds the Streamlit dashboard Docker image and deploys it to the server.
# It uses Docker socket mounting to build directly on the server (no SSH needed).
#
# Build Process:
# 1. Build Docker image from web_dashboard/Dockerfile
# 2. Tag image with commit SHA for version tracking
# 3. Stop and remove existing container (if running)
# 4. Deploy new container with environment variables from Woodpecker secrets
#
# Available Secrets (configure in Woodpecker - use lowercase names):
# - supabase_url: Your Supabase project URL
# - supabase_publishable_key: For user authentication
# - supabase_secret_key: For admin scripts and debug operations
#
# Note: Secrets are loaded using from_secret in the environment section
# Note: Repository must be marked as "Trusted" in Woodpecker settings to use volumes

steps:
  build-and-deploy:
    image: docker:24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Vancouver
      SUPABASE_URL:
        from_secret: supabase_url
      SUPABASE_PUBLISHABLE_KEY:
        from_secret: supabase_publishable_key
      SUPABASE_SECRET_KEY:
        from_secret: supabase_secret_key
    commands:
      # Set timezone (Pacific Time - handles PST/PDT automatically)
      - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      
      # Build Docker image from web_dashboard/Dockerfile
      - docker build -f web_dashboard/Dockerfile -t trading-dashboard:latest .
      - docker tag trading-dashboard:latest trading-dashboard:${CI_COMMIT_SHA}
      
      # Stop and remove existing container if it exists
      - docker stop trading-dashboard || true
      - docker rm trading-dashboard || true
      
      # Verify secrets are set
      - |
        if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_PUBLISHABLE_KEY" ] || [ -z "$SUPABASE_SECRET_KEY" ]; then
          echo "❌ ERROR: Missing required secrets"
          echo "Make sure supabase_url, supabase_publishable_key, and supabase_secret_key are set in Woodpecker"
          exit 1
        fi
      
      # Deploy new container (single line to avoid parsing issues)
      - docker run -d --name trading-dashboard --restart unless-stopped -p 8501:8501 -e SUPABASE_URL="$SUPABASE_URL" -e SUPABASE_PUBLISHABLE_KEY="$SUPABASE_PUBLISHABLE_KEY" -e SUPABASE_SECRET_KEY="$SUPABASE_SECRET_KEY" -e STREAMLIT_SERVER_HEADLESS=true -e STREAMLIT_BROWSER_GATHER_USAGE_STATS=false trading-dashboard:latest
      
      - echo "✅ Build and deployment complete!"
    when:
      event: push
      branch: [main, master]


