# Streamlit Dashboard Build and Deploy Pipeline
#
# This pipeline builds the Streamlit dashboard Docker image and deploys it to the server.
# It uses Docker socket mounting to build directly on the server (no SSH needed).
#
# Build Process:
# 1. Build Docker image from web_dashboard/Dockerfile
# 2. Tag image with commit SHA for version tracking
# 3. Stop and remove existing container (if running)
# 4. Deploy new container with environment variables from Woodpecker secrets
#
# Available Secrets (configure in Woodpecker - use lowercase names):
# - supabase_url: Your Supabase project URL
# - supabase_publishable_key: For user authentication
# - supabase_secret_key: For admin scripts and debug operations
# - ollama_base_url: (optional) Ollama API URL (default: http://host.docker.internal:11434)
# - ollama_model: (optional) Default AI model (default: mistral-nemo:12b)
# - ollama_enabled: (optional) Enable AI assistant (default: true)
#
# Note: Secrets are loaded using from_secret in the environment section
# Note: Repository must be marked as "Trusted" in Woodpecker settings to use volumes

steps:
  build-and-deploy:
    image: docker:24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/lance/ai-trading-www:/deploy_target
    environment:
      TZ: America/Vancouver
      SUPABASE_URL:
        from_secret: supabase_url
      SUPABASE_PUBLISHABLE_KEY:
        from_secret: supabase_publishable_key
      SUPABASE_SECRET_KEY:
        from_secret: supabase_secret_key
    commands:
      # Set timezone (Pacific Time - handles PST/PDT automatically)
      - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      
      # Format build timestamp in Pacific Time (PST/PDT)
      # CI_PIPELINE_STARTED is Unix timestamp, convert to Pacific Time
      # Use date command compatible with both GNU and BSD date
      - |
        if [ -n "$CI_PIPELINE_STARTED" ]; then
          export BUILD_TIMESTAMP=$(TZ=America/Vancouver date -d "@$CI_PIPELINE_STARTED" "+%Y-%m-%d %H:%M %Z" 2>/dev/null || TZ=America/Vancouver date -r "$CI_PIPELINE_STARTED" "+%Y-%m-%d %H:%M %Z" 2>/dev/null || TZ=America/Vancouver date "+%Y-%m-%d %H:%M %Z")
        else
          export BUILD_TIMESTAMP=$(TZ=America/Vancouver date "+%Y-%m-%d %H:%M %Z")
        fi
      
      # Build Docker image from web_dashboard/Dockerfile
      - docker build -f web_dashboard/Dockerfile -t trading-dashboard:latest .
      - docker tag trading-dashboard:latest trading-dashboard:${CI_COMMIT_SHA}
      
      # Stop and remove existing container if it exists
      - docker stop trading-dashboard || true
      - docker rm trading-dashboard || true
      
      # Verify secrets are set
      - |
        if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_PUBLISHABLE_KEY" ] || [ -z "$SUPABASE_SECRET_KEY" ]; then
          echo "❌ ERROR: Missing required secrets"
          echo "Make sure supabase_url, supabase_publishable_key, and supabase_secret_key are set in Woodpecker"
          exit 1
        fi
      
      # Deploy new container (single line to avoid parsing issues)
      # Added --add-host to allow connecting to Ollama and SearXNG on the host machine via host.docker.internal (Linux support)
      # NOTE: On Windows/Mac, host.docker.internal works natively. On Linux, you MUST add "--add-host=host.docker.internal:host-gateway"
      # Ollama and SearXNG settings can be overridden via Woodpecker secrets or environment variables
      - docker run -d --name trading-dashboard --restart unless-stopped -p 8501:8501 --add-host=host.docker.internal:host-gateway -e SUPABASE_URL="$SUPABASE_URL" -e SUPABASE_PUBLISHABLE_KEY="$SUPABASE_PUBLISHABLE_KEY" -e SUPABASE_SECRET_KEY="$SUPABASE_SECRET_KEY" -e BUILD_TIMESTAMP="$BUILD_TIMESTAMP" -e OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://host.docker.internal:11434}" -e OLLAMA_MODEL="${OLLAMA_MODEL:-mistral-nemo:12b}" -e OLLAMA_ENABLED="${OLLAMA_ENABLED:-true}" -e SEARXNG_BASE_URL="${SEARXNG_BASE_URL:-http://host.docker.internal:8080}" -e SEARXNG_TIMEOUT="${SEARXNG_TIMEOUT:-10}" -e SEARXNG_ENABLED="${SEARXNG_ENABLED:-true}" -e MAX_SEARCH_TICKERS="${MAX_SEARCH_TICKERS:-20}" -e STREAMLIT_SERVER_HEADLESS=true -e STREAMLIT_BROWSER_GATHER_USAGE_STATS=false trading-dashboard:latest
      
      # Deploy static files (auth callback HTML, cookie setting page, and login form)
      - echo "Deploying static files..."
      - mkdir -p /deploy_target/frontend
      - cp web_dashboard/static/auth_callback.html /deploy_target/frontend/auth_callback.html
      - cp web_dashboard/static/set_cookie.html /deploy_target/frontend/set_cookie.html
      - cp web_dashboard/static/login.html /deploy_target/frontend/login.html
      
      - echo "✅ Build and deployment complete!"
    when:
      event: push
      branch: [main, master]


